# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-08 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20171208_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='fav_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
