# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-08 03:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20171208_0321'),
        ('recipes', '0007_auto_20171208_0309'),
    ]

    operations = [
    ]
