# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-08 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_notification_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='tags',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
