# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-08 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_content_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('text', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='content',
            name='tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='contents',
            field=models.ManyToManyField(blank=True, to='recipes.Content'),
        ),
    ]
