# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-08 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20171208_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='contents',
            field=models.ManyToManyField(to='recipes.Content'),
        ),
    ]
