# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-08 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20171208_0615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloguser',
            name='picture',
        ),
        migrations.AddField(
            model_name='content',
            name='img',
            field=models.ImageField(blank=True, upload_to='content_img'),
        ),
        migrations.AlterField(
            model_name='content',
            name='text',
            field=models.CharField(max_length=10000),
        ),
    ]
