# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-08 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20171208_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='minute',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
