# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-09 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_content_minute'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='img',
            field=models.ImageField(upload_to='content_img'),
        ),
    ]
