# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-09 02:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_auto_20171209_0231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='img',
        ),
    ]
